### ISSUE TITLE
兄弟我有跟你一样的想法，你这个咋跑起来啊

### ISSUE THREAD

**Issue by xiaofeige** [avtion/goamis#1]
兄弟我有跟你一样的想法，你这个咋跑起来啊

**Comment by avtion** [comment]
直接 go run 就能跑，这只是我实验做的一个 demo，后面生产环境还是没有选择低代码的方案，维护难

**Comment by xiaofeige** [comment]
嗯嗯  跑起来了，但是我比较好奇，为啥会引入 bolt, 我理解已经静态embed进去了，就会在进程启动的时候放到内存里面了，没必要再去保存在bolt中吧？

**Comment by avtion** [comment]
新增页面的时候要把配置存储一下，可以直接写本地，这里我随便用 boltdb 存了

**Comment by lingr7** [comment]
跑起来长时间没有页面显示，可能是使用的cdn js失效了。我这边换成了https://cdn.baomitu.com/   这个cdn库
在amis.tmpl文件中添加
```

      <link crossorigin="anonymous"
    integrity="sha512-8k6Du9QAXuHA6YMQBNOBE7Cm0jUieUxuJF8rTXzSR9sDeHhUYZC3M2c4zVtybSkTLzi87CCajh1mRBk9Pu5QoA=="
    href="https://lib.baomitu.com/amis/2.2.0/sdk.css" rel="stylesheet">
  <link crossorigin="anonymous"
    integrity="sha512-HIqraZ9eej4z8MEytQHNx5g3r6bWhMiCrCcXtsEXEW397h5CujrEgrSzkTDRFyinjFH1wOO/DXIrcvsvHt7BgA=="
    href="https://lib.baomitu.com/amis/2.2.0/helper.css" rel="stylesheet">
  <link crossorigin="anonymous"
    integrity="sha512-VOt3BHFLnScxjSNMtYwJsQKkFvirxZUrUL1iVoBhajARE3hOp15xBMrR/qEjrhaJqTehLJf9aefAD2syTgrOug=="
    href="https://lib.baomitu.com/amis/2.2.0/iconfont.css" rel="stylesheet">
<script crossorigin="anonymous" integrity="sha512-fRGqNDWtGBIURkNvsM1yVGlzO7keyAaZcIAc84uTUPY2kdZhS/7Rc1/RHiFYvU2HiyeouXQCjhSVjMZqbgZPDw==" src="https://lib.baomitu.com/amis/2.2.0/sdk.js"></script>

```

**Comment by xiaofeige** [comment]
> 跑起来长时间没有页面显示，可能是使用的cdn js失效了。我这边换成了https://cdn.baomitu.com/ 这个cdn库 在amis.tmpl文件中添加
> 
> ```
> 
>       <link crossorigin="anonymous"
>     integrity="sha512-8k6Du9QAXuHA6YMQBNOBE7Cm0jUieUxuJF8rTXzSR9sDeHhUYZC3M2c4zVtybSkTLzi87CCajh1mRBk9Pu5QoA=="
>     href="https://lib.baomitu.com/amis/2.2.0/sdk.css" rel="stylesheet">
>   <link crossorigin="anonymous"
>     integrity="sha512-HIqraZ9eej4z8MEytQHNx5g3r6bWhMiCrCcXtsEXEW397h5CujrEgrSzkTDRFyinjFH1wOO/DXIrcvsvHt7BgA=="
>     href="https://lib.baomitu.com/amis/2.2.0/helper.css" rel="stylesheet">
>   <link crossorigin="anonymous"
>     integrity="sha512-VOt3BHFLnScxjSNMtYwJsQKkFvirxZUrUL1iVoBhajARE3hOp15xBMrR/qEjrhaJqTehLJf9aefAD2syTgrOug=="
>     href="https://lib.baomitu.com/amis/2.2.0/iconfont.css" rel="stylesheet">
> <script crossorigin="anonymous" integrity="sha512-fRGqNDWtGBIURkNvsM1yVGlzO7keyAaZcIAc84uTUPY2kdZhS/7Rc1/RHiFYvU2HiyeouXQCjhSVjMZqbgZPDw==" src="https://lib.baomitu.com/amis/2.2.0/sdk.js"></script>
> ```

我直接把sdk  打包到go代码里面了，不需要CDN了，加载起来贼快

**Comment by luengwaiban** [comment]
> 直接 go run 就能跑，这只是我实验做的一个 demo，后面生产环境还是没有选择低代码的方案，维护难

你好我想问一下，最后生产环境用了什么方案呢？维护难具体是在哪几个方便呀？
